services:
  - type: web
    name: heal-nova
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: <yahan php artisan key:generate --show ka output daalo>
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: <your-db-host>
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: <your-db-name>
      - key: DB_USERNAME
        value: <your-db-username>
      - key: DB_PASSWORD
        value: <your-db-password>
